//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaLafise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Poliza
    {
        public int IdPoliza { get; set; }
        public string Cliente { get; set; }
        [DisplayName("Fecha de Adquisición")]
        public System.DateTime FechaAdquisicion { get; set; }
        [DisplayName("Fecha Vencimiento")]
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        [DisplayName("Seguro")]
        public Nullable<int> IdSeguro { get; set; }
        [DisplayName("Seguro")]
        public virtual Seguro Seguro { get; set; }
    }
}
